#!/bin/bash

echo "                                                                       "
echo "*      .     .  *        *        .          *      .           *     *"
echo "                                                                       "
echo "       .                .        .               *      .      *     . "
echo "                                                                       "
echo ".  *         .  *           S E T U P    *          *           .      "
echo "         *                .P L U G I N                      *          "
echo "    .              *   .        .            *        .            *   "
echo " .            .                                                        "
echo "         *          .    *           *     .           *           *   "
echo "                                                                       "

while [[ -z $plugin_name ]]; do
	read -rep $'What\'s the name of your plugin?\n> ' plugin_name
done

read -rep $'setup\'s file name:\n> '"(${pluginname// /}.js)"' ' plugin_file_name

# default file name if empty
if [[ -z "$plugin_file_name" ]]; then
	plugin_file_name=${plugin_name// /}
# remove js extension if exists
elif [[ "$plugin_file_name" == .js ]]; then
	plugin_file_name="${plugin_file_name%.}"
fi

read -rep $'Enter author name:\n> ' plugin_author

read -rep $'What\'s the description of your plugin?\n> ' plugin_description

read -rep $'Would you like to include your Github account in plugin details? \n(y/n) > ' accept_github_link

if [[ ${accept_github_link,,} == 'y' ]]; then
	read -rep $'Enter your Github account:\n> ' github_link
fi

SETUP_FILE_LOCATION='development'

mkdir -p $SETUP_FILE_LOCATION

rm -f $SETUP_FILE_LOCATION/$plugin_file_name.js && touch $SETUP_FILE_LOCATION/$plugin_file_name.js

cat boilerplate.txt > /$plugin_name.js

rm -f $SETUP_FILE_LOCATION/meta.js touch $SETUP_FILE_LOCATION/meta.json

echo '{"author":"'"$plugin_author"'","description":"'"$plugin_description"'","targetlocation":"'"$plugin_file_name"'"}' > $SETUP_FILE>

echo 'your setup file was generated in /'"${SETUP_FILE_LOCATION}/${plugin_file_name}"' '
