#!/bin/bash

echo "                                                                       "
echo "*      .     .  *        *        .          *      .           *     *"
echo "                                                                       "
echo "       .                .        .               *      .      *     . "
echo "                                                                       "
echo ".  *         .  *             SETUP    *          *                    "
echo "         *                 .                                *          "
echo "    .              *   .        .            *        .            *   "
echo " .            .                                                        "
echo "         *          .    *           *     .           *           *   "
echo "                                                                       "

read -rep $'What\'s the name of your plugin?\n> ' plugin_name

read -rep $'What\'s the description of your plugin?\n> ' plugin_description

read -rep $'Would you like to include your Github account in plugin details? \n(y/n) > ' accept_github_link

read -rep $'Enter your Github account \n > ' github_link

read -rep $'What browser do you prefer to test your plugin?\n> ' browser_name
