#!/bin/bash

echo "                                                                       "
echo "*      .     .  *        *        .          *      .           *     *"
echo "                                                                       "
echo "       .                .        .               *      .      *     . "
echo "                                                                       "
echo ".  *         .  *           S E T U P    *          *           .      "
echo "         *                .P L U G I N                      *          "
echo "    .              *   .        .            *        .            *   "
echo " .            .                                                        "
echo "         *          .    *           *     .           *           *   "
echo "                                                                       "

# keep asking until it gets valid plugin name
while [[ -z $plugin_name ]]; do
	read -rep $'What\'s the name of your plugin?\n> ' plugin_name
done

# replace space with underscore
plugin_name=${plugin_name// /_}

# to lowercase
plugin_name="${plugin_name,,}"

# ask for file name and suggest a default file name
read -rep $'setup\'s file name:\n> '"($plugin_name.js)"' ' plugin_file_name

# default filename if file name is not empty
if [[ ! -z "$plugin_file_name" ]]; then
	# remove .js extension if extension exist
	plugin_name="${plugin_file_name%.}"

	plugin_name=${plugin_name// /_}
fi

read -rep $'Enter author name or your github account name:\n> ' plugin_author

read -rep $'What\'s the description of your plugin?\n> ' plugin_description

# gets output directory according to this file location
OUTPUT_DIRECTORY_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/../../output"

# create output directory if not exists
mkdir -p $OUTPUT_DIRECTORY_PATH

# relative to absolute path
OUTPUT_DIRECTORY_PATH="$(cd ${OUTPUT_DIRECTORY_PATH}; pwd)"

PLUGIN_FILE_PATH="${OUTPUT_DIRECTORY_PATH}/${plugin_name}.js"

rm -f $PLUGIN_FILE_PATH && touch $PLUGIN_FILE_PATH

# copy template and change class name to the plugin name
sed "s/Template/$plugin_name/" $OUTPUT_DIRECTORY_PATH/../lib/development/template.js > $PLUGIN_FILE_PATH

# metadata about plugin
echo '{"author":"'"$plugin_author"'", "verion":"1.0"}' > $OUTPUT_DIRECTORY_PATH/config.json

# setup readme
echo -e "# $plugin_name \n$plugin_description \n\n# contributors \n\n* Author $plugin_author" > $OUTPUT_DIRECTORY_PATH/README.md

echo -e '\nYour setup file was generated in '"$OUTPUT_DIRECTORY_PATH/${plugin_name}.js"' '