#!/bin/bash

echo "                                                                       "
echo "*      .     .  *        *        .          *      .           *     *"
echo "                                                                       "
echo "       .                .        .               *      .      *     . "
echo "                                                                       "
echo ".  *         .  *           S E T U P    *          *           .      "
echo "         *                .P L U G I N                      *          "
echo "    .              *   .        .            *        .            *   "
echo " .            .                                                        "
echo "         *          .    *           *     .           *           *   "
echo "                                                                       "

# keep asking until it gets valid plugin name
while [[ -z $plugin_name ]]; do
	read -rep $'What\'s the name of your plugin?\n> ' plugin_name
done

# replace space with underscore
plugin_name=${plugin_name// /_}

# to lowercase
plugin_name="${plugin_name,,}"

# ask for file name and suggest a default file name
read -rep $'setup\'s file name:\n> '"($plugin_name.js)"' ' plugin_file_name

# default filename if file name is not empty
if [[ ! -z "$plugin_file_name" ]]; then
	# remove .js extension if extension exist
	plugin_name="${plugin_file_name%.}"
	plugin_name=${plugin_name// /_}
fi

read -rep $'Enter author name or your github account name:\n> ' plugin_author

read -rep $'What\'s the description of your plugin?\n> ' plugin_description

# gets output directory according to this file location
SETUP_FILE_LOCATION="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/../../output"

# relative to absolute path
ABSOLUTE_SETUP_PATH="$(cd ${SETUP_FILE_LOCATION}; pwd)"

FILE_NAME_PATH="${ABSOLUTE_SETUP_PATH}/${plugin_file_name}.js"

mkdir -p $ABSOLUTE_SETUP_PATH

rm -f $FILE_NAME_PATH && touch $FILE_NAME_PATH

# copy template and change class name to the plugin name
sed "s/Template/${plugin_name// /_}/" $ABSOLUTE_SETUP_PATH/../plugin/development/template.js > $FILE_NAME_PATH

# metadata about plugin
echo '{"author":"'"$plugin_author"'","description":"'"$plugin_description"'","verion":"1.0"}' > $ABSOLUTE_SETUP_PATH/config.json

echo -e '\nYour setup file was generated in '"$ABSOLUTE_SETUP_PATH/${plugin_file_name}.js"' '