#!/bin/bash

echo "                                                                       "
echo "*      .     .  *        *        .          *      .           *     *"
echo "                                                                       "
echo "       .                .        .               *      .      *     . "
echo "                                                                       "
echo ".  *         .  *           S E T U P    *          *           .      "
echo "         *                .P L U G I N                      *          "
echo "    .              *   .        .            *        .            *   "
echo " .            .                                                        "
echo "         *          .    *           *     .           *           *   "
echo "                                                                       "

# keep asking until it gets valid plugin name
while [[ -z $plugin_name ]]; do
	read -rep $'What\'s the name of your plugin?\n> ' plugin_name
done

# ask for file name and suggest a default file name
read -rep $'setup\'s file name:\n> '"(${plugin_name// /_}.js)"' ' plugin_file_name

# default filename if file name is empty
if [[ -z "$plugin_file_name" ]]; then
	# replace spaces with underscore
	plugin_file_name=${plugin_name// /_}
# remove .js extension if extension exist
elif [[ "$plugin_file_name" == .js ]]; then
	plugin_file_name="${plugin_file_name%.}"
fi

read -rep $'Enter author name:\n> ' plugin_author

read -rep $'What\'s the description of your plugin?\n> ' plugin_description

read -rep $'Would you like to include your Github account in plugin details? \n(y/n) > ' accept_github_link

# covert accept github link to lowercase and compare 
if [[ ${accept_github_link,,} == 'y' ]]; then
	read -rep $'Enter your Github account:\n> ' github_link
fi

# gets output directory according to this file location
SETUP_FILE_LOCATION="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/../../output"

mkdir -p $SETUP_FILE_LOCATION

rm -f $SETUP_FILE_LOCATION/$plugin_file_name.js && touch $SETUP_FILE_LOCATION/$plugin_file_name.js

cat plugin/template.js > $SETUP_FILE_LOCATION/$plugin_file_name.js

rm -f $SETUP_FILE_LOCATION/meta.js && touch $SETUP_FILE_LOCATION/meta.json

echo '{"author":"'"$plugin_author"'","description":"'"$plugin_description"'","targetlocation":"'"$plugin_file_name"'"}' > $SETUP_FILE_LOCATION/meta.json

# relative to absolute path
ABSOLUTE_SETUP_PATH="$(cd ${SETUP_FILE_LOCATION}; pwd)"

echo 'your setup file was generated in '"$ABSOLUTE_SETUP_PATH/${plugin_file_name}.js"' '
